- name: Setup contabo instance
  hosts: contabo
  become: yes
  tasks:
    - name: Update APT package list
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present
    - name: Install required package
      apt:
        name:
          - wget
          - curl
          - git
          - net-tools
          - neofetch
        state: present